# Generated by Django 5.2.4 on 2025-08-12 14:07

import bson.objectid
import django_mongodb_backend.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdField(db_column='_id', default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('items', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.ObjectIdField(), default=list)),
                ('table_num', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('served', 'Served'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
