# Generated by Django 5.2.4 on 2025-08-12 14:07

import bson.objectid
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdField(db_column='_id', default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('parent', django_mongodb_backend.fields.ObjectIdField(blank=True, null=True)),
                ('path', models.CharField(editable=False, max_length=150)),
                ('ancestors', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.ObjectIdField(), blank=True, default=list, editable=False, size=8)),
            ],
            options={
                'db_table': 'menu_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdField(db_column='_id', default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category_id', django_mongodb_backend.fields.ObjectIdField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'menu_items',
                'managed': False,
            },
        ),
    ]
