# Generated by Django 5.2.4 on 2025-09-25 14:22

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('table_num', models.IntegerField(blank=True, null=True)),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(default='eur', max_length=10)),
                ('order_ids', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.ObjectIdField(), default=list)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('payer_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['stripe_payment_intent_id'], name='payments_stripe__6cb0ea_idx'), models.Index(fields=['table_num'], name='payments_table_n_b9de54_idx'), models.Index(fields=['paid_at'], name='payments_paid_at_c989bb_idx'), models.Index(fields=['created_at'], name='payments_created_e3a130_idx')],
            },
        ),
    ]
