# Generated by Django 5.2.4 on 2025-10-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
