# Generated by Django 5.2.4 on 2025-08-12 14:07

import bson.objectid
import django_mongodb_backend.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdField(db_column='_id', default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('table_number', models.IntegerField(editable=False)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
            ],
            options={
                'db_table': 'tables',
                'managed': False,
            },
        ),
    ]
